### ISSUE TITLE
[Feat] 누끼 기능 개선 #1

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MC2-TEAM10_BURIBURI#1]
# ✏️Description
누끼 기능 개선

# 🛠️Todo
- [x] Scan1_Oliver : 제일 큰 덩어리 하나만 남기고 없애기
- [x] Scan2_Oliver : 5초는 기니까 속도 개선하기
- [x] Scan3_Oliver: 그림의 상하좌우 잉여 여백 없애기: 누끼 딴 이미지에서 덩어리의 상하좌우 끝이 이미지 네모의 상하좌우 경계와 일치하게.
- [x] Scan4_Oliver : 함수 Git에 넣기
- [ ] Scan5_Oliver: 배경 제거한 PNG 사진을 데이터 파일로 얻어내는 함수(1), 그리고 그 파일을 파일매니저에 저장하는 함수(2) 명확히 하기
- [ ] Scan6_Oliver: 사진의 orientation 정보 제대로 고려해서 모든 단계에서 일관된 방향의 결과물 얻기
- [ ] Scan7_Oliver : (텍스처 입힌 USDZ)(혹은 Path? 아직 불명확) 저장하는 함수 만들기
- [ ] Scan8_Oliver : 배경이 제대로 없어진 것 맞나? 배경 날리는 코드 재검토
- [ ] Scan9_Oliver : 함수 비동기로 하기

# ⚙️ETC
- 추가적인 설명
