### ISSUE TITLE
[Feat] AlbumView 관련 #4

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MC2-TEAM10_BURIBURI#3]
# ✏️Description
AlbumView 관련 기능 개발

# 🛠️Todo
- [x] Album1_GaOn : 편집을 할 수 있는 부모용 AlbumView
- [ ] Album2_GaOn : 오브젝트를 띄우기만 할 수 있는 아이용 AlbumView
- [ ] Album3_GaOn : AlbumView sheet으로 띄울 때 opacity 주기와 Animation 유지되게 하기

# ⚙️ETC
- 추가적인 설명
