### ISSUE TITLE
[Feat] 2D extrusion으로 3D 객체 생성하기

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MC2-TEAM10_BURIBURI#4]
# ✏️ Description
BezierPath와 SCNShape 활용해서 2D extrusion으로 3D 객체 생성하기

# 🛠️ Todo
- [x] ext1_PEPE : BezierPath 받아서 SCNShape 생성
- [x] ext2_PEPE : Texture 씌우기
- [x] ext3_PEPE : 생성된 3D 객체를 AR에 띄워보기
- [x] ext4_PEPE : 3D 객체의 저장 형식 알아보기 (SCNShape, .usdz, ...)
- [x] ext5_PEPE: 옆면 채우기 = 지그재그 or 단색 (분홍)

# ⚙️ ETC
