### ISSUE TITLE
[Feat] 변환 함수 비동기 처리, 세션 멈춤 현상 해결, 스캔 개선

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MC2-TEAM10_BURIBURI#66]
# ✏️ Description
출시 전 기술적 개선의 일부로 아래와 같은 작업을 합니다

# 🛠️ Todo
- [ ] OliverSession : 스캔 시간 몇 초 동안 화면 안 멈추게 비동기로 바꾸기
- [ ] OliverSession : AR과 스캔 화면 전환에 dismiss 적용하고 화면 멈춤 해결하기
- [ ] 스캔 정확도 올릴 수 있으면 올려보기

# ⚙️ ETC
-

**Comment by oliver-or-not** [comment]
비동기 처리한 함수가 실행되는 동안 빙글빙글 표시 등을 추가하는 것을 고려할 수 있습니다.
