### ISSUE TITLE
해결하지 못한 문제들

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MC2-TEAM10_BURIBURI#68]
# ✏️ Description
dismiss로 바꿔도 왜 AR 화면 관련 메모리 점유가 해제되지 않을까? 앱이 튕긴다.
테두리가 복잡하면 왜 소환이 안 될까? 다각형 그리기 알고리즘에 무슨 문제가 있길래?
처음 소환할 때 렉이 너무 오래 걸린다. 왜일까?

# 🛠️ Todo
- [ ] OliverMemory : 메모리 누수 해결하기
- [ ] OliverMemory : 테두리 복잡한 것도 소환되게 노력해보기
- [ ] OliverMemory : 처음 소환할 때 렉 걸리는 것 개선해보기
- [ ] OliverMemory : 스캔 화면에서 스캔 기다리는 도중에 AR 화면으로 넘어가는 등 다른 작업 못하게 하기
